### ISSUE TITLE
I feel like finding a girlfriend is harder than getting a FAAMG offer

### ISSUE THREAD

**Issue by dtrager02** [saadsheriff/discord-door#10]
I feel like this sub is all about internships and so on, but as a CS student I have also noticed something. We don’t have a lot of girls in CS classes and this makes it very hard to meet girls compared to students in other majors. I don’t know how many of you can relate but given that we spend much of our time I computer labs, grinding Leetcode , working on side projects and so on, I don’t get exposure to more women and as a result I haven’t had a huge dating window, let alone get a girlfriend. This is kinda scary since college is where you are supposed to meet people for this kind of stuff and once I start working full time I am afraid it’s gonna be even harder.

On the other hand I have interned with two Big N/FAAMG and I feel like I know what I need to do to get a big N offer. For girls on the other hand, I can’t seem to hack it. Can any of you relate?

**Comment by dtrager02** [comment]
issue still not resolved. solved every leetcode hard but still single

**Comment by jacob-zietek** [comment]
Issue closed. Solution posted.

**Comment by saadsheriff** [comment]
Hey @dtrager02 thanks for raising this issue! Unfortunately, our team is not equipped well enough to answer your query. We do welcome open-source chads to contribute to help resolve this, though 🚪
